---
  - name: Update apt
    become: true
    apt:
      update_cache: yes

  - name: Upgrade apt
    become: true
    apt:
      upgrade: yes

  - name: Remove dependencies that are no longer required
    become: yes
    apt:
      autoremove: yes

  - name: Install npm
    become: true
    apt:
      name: npm
      update_cache: yes

  - name: Install n
    become: yes
    npm:
      name: n
      global: yes
      production: yes

  - name: Install nodejs v13.8.0
    become: yes
    shell: n 13.8.0

  - name: Install pm2
    become: true
    npm:
      name: pm2
      global: yes
      production: yes
      state: present