apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-hello-world-app-deployment
  labels:
    app: simple-hello-world-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-hello-world-app
  template:
    metadata:
      labels:
        app: simple-hello-world-app
    spec:
      containers:
        - name: simple-hello-world-app
          image: docker.io/daithanhtran2912/simple-hello-world-app:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: simple-hello-world-app-lb
spec:
  selector:
    app: simple-hello-world-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80